services:
  scheduler:
    container_name: quantops-scheduler
    shm_size: '4gb'
    build:
      context: ..
      dockerfile: scheduler/Dockerfile
    volumes:
      - ../db:/app/db
      - ../logs:/app/logs
      - ../secrets:/app/secrets:ro
      - ../codes:/app/codes
      - ../strategies:/app/strategies
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=/app
      - TZ=Asia/Seoul
      - DISCORD_WEBHOOK_FINANCIAL=${DISCORD_WEBHOOK_FINANCIAL}
      - DISCORD_WEBHOOK_SELECTION=${DISCORD_WEBHOOK_SELECTION}
      - DISCORD_WEBHOOK_TRADE=${DISCORD_WEBHOOK_TRADE}
    restart: unless-stopped
    tty: true
    stdin_open: true
